schema-version: v2
kind: plugin
metadata:
  name: serverless
  display-name: serverless
  description: Descreva seu plugin explicando o propósito
  picture: plugin.png
  version: 0.0.6
spec:
  type: app
  compatibility:
    - javascript
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - TypeScript
    - AWS Lambda
  stk-projects-only: false
  inputs:
    - label: Project name (everything in lowercase and underscore-separated)
      name: project_name
      type: text
      pattern: '^[a-z]+(_[a-z]+)*$'

    - label: Add pg package, to access postgre database?
      name: add_pg
      type: bool
